### PR TITLE
Update composer.json for Laravel 6

### PR DESCRIPTION
**Pull request by jimmitjoo**
Made it work with Laravel 6 and added phpunit 8.

### CODE REVIEW

**Comment by djam90** [comment]
Is there an ETA for merging this? My project is using Laravel 6 and this is stopping me from using this package, and so it is stopping me from using Contentful at all.

**Comment by stakahashi** [comment]
@realityking 
Have you confirmed this PR?
We are also using Laravel 6.

**Comment by dborsatto** [comment]
Hey @stakahashi et all,

neither Rouven nor I work on this project any more. Your best bet is probably to get in touch through their [Twitter](https://twitter.com/contentful) or [support page](https://www.contentful.com/support/).

Cheers,

Davide

**Comment by stakahashi** [comment]
@dborsatto Contacted support. Thanks :)

**Comment by matthew-contentful** [comment]
Made this change in another PR. Thanks for the contribution!

**Pull request closed without merging**
