### PR TITLE
allow php 8

### PR DESCRIPTION
**Pull request by marvinosswald**
i'm going to create a series of pr all over related packages to https://github.com/contentful/contentful-laravel

prs:

- https://github.com/contentful/contentful-core.php/pull/44
- https://github.com/contentful/contentful-laravel/pull/40
- https://github.com/contentful/rich-text.php/pull/56
- https://github.com/contentful/contentful.php/pull/296

### CODE REVIEW

**Comment by ArondeParon** [comment]
Is there anything blocking this PR? Would be really great if PHP 8 can be supported.

**Comment by Sebb767** [comment]
Hi @ArondeParon ,

PHP8 support should be released this week :)

> Is there anything blocking this PR?

Most Repos already have a `php8-support-dev` version, but I need to update a bit (refresh CI, run code linter, check whether everything works), so I'll probably do it in my own commit. This repo does depend on the release `contentful/contentful`, which is mostly done (see https://github.com/contentful/contentful.php/tree/php8-support ) - once that is released, I'll update this repo.

**Comment by ArondeParon** [comment]
Great news, thanks for the update!

**Comment by Sebb767** [comment]
With 8.1.0, PHP8 is now officially supported in this library and all Contentful dependencies :)

As with the other PRs, I added the support manually, as the CI, README etc.. needed updating. Still, thank you very much for your PRs, @marvinosswald ! :)

**Pull request closed without merging**
